name = "codenus"
env = "local"
debug = True
key = "dfhfUGFKgk@glJKKskkefo648l964kcvnknfjlkd68#49ldfxkcnvkmxcv56738"
public_folder = "public"
ipHeader = "cf-connecting-ip"
cors_allow = ["*"]
cacheDriver='file'
admin_subdomain="admin"
